name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go  1.17.10
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.10
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Go module download
      run: go mod download
      
    - name: Go Test
      run: go test -v -cover -covermode=atomic ./...
